"""types

Revision ID: 40c5d4bff501
Revises: 9eeabaccf7e5
Create Date: 2025-01-25 01:33:06.563862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c5d4bff501'
down_revision: Union[str, None] = '9eeabaccf7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_category', sa.Column('type', sa.Enum('METHOD_DOC', 'NORM_DOC', 'STUDY_MATERIAL', 'PHOTO', 'VIDEO', 'PRESENTATION', name='mediatype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_category', 'type')
    # ### end Alembic commands ###
